version: "2"
services:
  jeopardy:
    restart: unless-stopped
    build:
      context: '..'
      dockerfile: 'docker/Dockerfile'
    ports:
      - "3000:3000"
    environment:
      INITDB: 2021
      MULTI: 1
    volumes:
      - ../gameserver/public:/opt/jeopardy/virtual7jeopardy/gameserver/public
      - ../gameserver/server.js:/opt/jeopardy/virtual7jeopardy/gameserver/server.js
      - ../gameserver/db_initialize_2021.js:/opt/jeopardy/virtual7jeopardy/gameserver/db_initialize_2021.js
      - ./db:/opt/jeopardy/virtual7jeopardy/gameserver/db/